In [1]:
import polars as pl
import numpy as np
from scipy import stats
import altair as alt

In [2]:
df = pl.scan_parquet("data/data_bias.parquet")

In [3]:
def ci_lower(x, confidence = .95):
    x = x.to_numpy()
    n = len(x)

    mean = np.mean(x)
    se = stats.sem(x)
    ci = se * stats.t.pdf((1 + confidence) / 2, n-1)

    return mean - ci

def ci_upper(x, confidence = .95):
    x = x.to_numpy()
    n = len(x)

    mean = np.mean(x)
    se = stats.sem(x)
    ci = se * stats.t.pdf((1 + confidence) / 2, n-1)

    return mean + ci

In [4]:
df.collect()

shape: (31_496, 12)
┌───────────┬──────────┬──────────┬──────────┬───┬──────┬──────────────┬──────┬───────┐
│ train acc ┆ train f1 ┆ test acc ┆ test f1  ┆ … ┆ bias ┆ distribution ┆ seed ┆ model │
│ ---       ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---  ┆ ---          ┆ ---  ┆ ---   │
│ f64       ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64  ┆ str          ┆ i32  ┆ str   │
╞═══════════╪══════════╪══════════╪══════════╪═══╪══════╪══════════════╪══════╪═══════╡
│ 0.830889  ┆ 0.845105 ┆ 0.83     ┆ 0.844037 ┆ … ┆ 3.0  ┆ moons        ┆ 42   ┆ Tree  │
│ 0.830889  ┆ 0.845231 ┆ 0.83     ┆ 0.842884 ┆ … ┆ 3.0  ┆ moons        ┆ 42   ┆ Tree  │
│ 0.829333  ┆ 0.843265 ┆ 0.848    ┆ 0.859779 ┆ … ┆ 3.0  ┆ moons        ┆ 42   ┆ Tree  │
│ 0.830444  ┆ 0.843999 ┆ 0.838    ┆ 0.852995 ┆ … ┆ 3.0  ┆ moons        ┆ 42   ┆ Tree  │
│ 0.831556  ┆ 0.845747 ┆ 0.824    ┆ 0.838235 ┆ … ┆ 3.0  ┆ moons        ┆ 42   ┆ Tree  │
│ …         ┆ …        ┆ …        ┆ …        ┆ … ┆ …    ┆ …            ┆ …    ┆ …     │
│ 0.999444  ┆ 0.999259 ┆ 0.594    ┆ 0.472727 ┆ … ┆ 0.25 ┆ circles      ┆ 179  ┆ Tree  │
│ 0.998054  ┆ 0.997401 ┆ 0.61     ┆ 0.498715 ┆ … ┆ 0.25 ┆ circles      ┆ 179  ┆ Tree  │
│ 0.999722  ┆ 0.999628 ┆ 0.58     ┆ 0.487805 ┆ … ┆ 0.25 ┆ circles      ┆ 179  ┆ Tree  │
│ 0.99638   ┆ 0.995133 ┆ 0.6      ┆ 0.484536 ┆ … ┆ 0.25 ┆ circles      ┆ 179  ┆ Tree  │
│ 0.995288  ┆ 0.993706 ┆ 0.608    ┆ 0.5      ┆ … ┆ 0.25 ┆ circles      ┆ 179  ┆ Tree  │
└───────────┴──────────┴──────────┴──────────┴───┴──────┴──────────────┴──────┴───────┘

In [5]:
cols = ["train acc", "train f1", "test acc", "test f1", 
               "adv acc", "adv f1", "adv distance"]

def agg_metrics(cols):
    res = []
    for col in cols:
        res.extend([
            pl.col(col).mean().alias(f"{col}_mean"),
            pl.col(col).std().alias(f"{col}_std"),
            pl.col(col).map_batches(ci_lower, return_dtype=pl.Float32, returns_scalar=True).alias(f"{col}_ci_lb"),
            pl.col(col).map_batches(ci_upper, return_dtype=pl.Float32, returns_scalar=True).alias(f"{col}_ci_ub"),
        ])
    return res

In [ ]:
df_stats = df.select(pl.exclude("seed")).group_by(
    pl.col("distribution"),
    pl.col("model"),
    pl.col("depth"),
    pl.col("bias")
).agg(
    agg_metrics(cols)
).sort([
    pl.col("distribution"),
    # pl.col("seed"),
    pl.col("depth"),
    pl.col("bias")
])

# df.with_columns(pl.col("train acc").gr)

In [10]:
df_stats.collect()

shape: (418, 32)
┌──────────────┬───────┬───────┬──────┬───┬──────────────┬─────────────┬─────────────┬─────────────┐
│ distribution ┆ model ┆ depth ┆ bias ┆ … ┆ adv distance ┆ adv distanc ┆ adv distanc ┆ adv distanc │
│ ---          ┆ ---   ┆ ---   ┆ ---  ┆   ┆ _mean        ┆ e_std       ┆ e_ci_lb     ┆ e_ci_ub     │
│ str          ┆ str   ┆ i32   ┆ f64  ┆   ┆ ---          ┆ ---         ┆ ---         ┆ ---         │
│              ┆       ┆       ┆      ┆   ┆ f64          ┆ f64         ┆ f32         ┆ f32         │
╞══════════════╪═══════╪═══════╪══════╪═══╪══════════════╪═════════════╪═════════════╪═════════════╡
│ circles      ┆ Tree  ┆ 1     ┆ 0.25 ┆ … ┆ 0.220577     ┆ 0.010613    ┆ 0.220306    ┆ 0.220849    │
│ circles      ┆ Tree  ┆ 1     ┆ 0.5  ┆ … ┆ 0.156398     ┆ 0.008529    ┆ 0.156188    ┆ 0.156609    │
│ circles      ┆ Tree  ┆ 1     ┆ 0.75 ┆ … ┆ 0.142937     ┆ 0.008849    ┆ 0.142719    ┆ 0.143156    │
│ circles      ┆ Tree  ┆ 1     ┆ 1.0  ┆ … ┆ 0.17766      ┆ 0.009086    ┆ 0.177436    ┆ 0.177885    │
│ circles      ┆ Tree  ┆ 1     ┆ 1.25 ┆ … ┆ 0.169435     ┆ 0.009591    ┆ 0.169198    ┆ 0.169672    │
│ …            ┆ …     ┆ …     ┆ …    ┆ … ┆ …            ┆ …           ┆ …           ┆ …           │
│ moons        ┆ Tree  ┆ 12    ┆ 2.0  ┆ … ┆ 0.280828     ┆ 0.055089    ┆ 0.278376    ┆ 0.28328     │
│ moons        ┆ Tree  ┆ 12    ┆ 2.25 ┆ … ┆ 0.349911     ┆ 0.033049    ┆ 0.348125    ┆ 0.351697    │
│ moons        ┆ Tree  ┆ 12    ┆ 2.5  ┆ … ┆ 0.3472       ┆ 0.04399     ┆ 0.345242    ┆ 0.349158    │
│ moons        ┆ Tree  ┆ 12    ┆ 3.0  ┆ … ┆ 0.3472       ┆ 0.04399     ┆ 0.345242    ┆ 0.349158    │
│ moons        ┆ Tree  ┆ 13    ┆ 1.5  ┆ … ┆ 0.229522     ┆ 0.024057    ┆ 0.228687    ┆ 0.230358    │
└──────────────┴───────┴───────┴──────┴───┴──────────────┴─────────────┴─────────────┴─────────────┘

In [12]:
base = alt.Chart(
    df_stats.collect()
)

scale = alt.Scale(
    domain=["train acc_mean", "test acc_mean", "adv distance_mean"], 
    range=["blue", "red", "purple"]
)


dash_scale = alt.Scale(
    domain=["train acc_mean", "test acc_mean", "adv distance_mean"],
    range=[[2, 4], [1, 0], [8, 4]]  # [dash_length, gap_length]
)

# Chart for accuracy metrics (left y-axis)
acc_chart = base.mark_line(strokeWidth=2).transform_fold(
    fold=["train acc_mean", "test acc_mean"],
    as_=["variable", "value"]
).encode(
    x=alt.X("depth:Q").title("Depth"),
    y=alt.Y('value:Q').title("Accuracy").scale(zero=False),
    color=alt.Color('variable:N', scale=scale, title="Metric"),
    strokeDash=alt.StrokeDash('variable:N', scale=dash_scale)
)


# Chart for adversarial distance (right y-axis)
adv_chart = base.mark_line(strokeWidth=2).transform_fold(
    fold=["adv distance_mean"],
    as_=["variable", "value"]
).encode(
    x=alt.X("depth:Q").title("Depth"),
    y=alt.Y('value:Q').title("Adversarial Distance").axis(orient='right').scale(zero=False),
    color=alt.Color('variable:N', scale=scale, title="Metric"),
    strokeDash=alt.StrokeDash('variable:N', scale=dash_scale)

)

ci_band0 = base.mark_area(
    opacity=0.3,
    interpolate="basis",
).encode(
    x="depth:Q",
    y=alt.Y("train acc_ci_lb:Q").axis(title="Accuracy", orient="left"),
    y2=alt.Y2("train acc_ci_ub:Q"),
    color = alt.value("blue"),
)

ci_band1 = base.mark_area(
    opacity=0.3,
    interpolate="basis",
).encode(
    x="depth:Q",
    y=alt.Y("test acc_ci_lb:Q").axis(title="Accuracy", orient="left"),
    y2=alt.Y2("test acc_ci_ub:Q"),
    color = alt.value("red")
)

ci_band2 = base.mark_area(
    opacity=0.3,
    interpolate="basis",
).encode(
    x="depth:Q",
    y=alt.Y("adv distance_ci_lb:Q").axis(orient="right"),
    y2=alt.Y2("adv distance_ci_ub:Q"),
    color = alt.value("purple")
)

alt.layer(acc_chart + ci_band0 + ci_band1, adv_chart + ci_band2).resolve_scale(
    y='independent'
).facet(
    row="distribution",
    column="bias"
).resolve_scale(
    x="independent",
    y="independent"
)

alt.FacetChart(...)