In [1]:
import polars as pl
import numpy as np
from scipy import stats
import altair as alt

In [2]:
df = pl.scan_parquet("data/data_bias.parquet")

In [3]:
def ci_lower(x, confidence = .95):
    x = x.to_numpy()
    n = len(x)

    mean = np.mean(x)
    se = stats.sem(x)
    ci = se * stats.t.pdf((1 + confidence) / 2, n-1)

    return mean - ci

def ci_upper(x, confidence = .95):
    x = x.to_numpy()
    n = len(x)

    mean = np.mean(x)
    se = stats.sem(x)
    ci = se * stats.t.pdf((1 + confidence) / 2, n-1)

    return mean + ci

In [4]:
df.collect()

shape: (23_800, 13)
┌───────────┬──────────┬──────────┬──────────┬───┬──────┬──────────────┬──────┬───────┐
│ train acc ┆ train f1 ┆ test acc ┆ test f1  ┆ … ┆ bias ┆ distribution ┆ seed ┆ model │
│ ---       ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---  ┆ ---          ┆ ---  ┆ ---   │
│ f64       ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64  ┆ i64          ┆ i32  ┆ str   │
╞═══════════╪══════════╪══════════╪══════════╪═══╪══════╪══════════════╪══════╪═══════╡
│ 0.622222  ┆ 0.515619 ┆ 0.6      ┆ 0.493506 ┆ … ┆ 0.1  ┆ 0            ┆ 42   ┆ Tree  │
│ 0.622222  ┆ 0.517108 ┆ 0.6      ┆ 0.50463  ┆ … ┆ 0.1  ┆ 0            ┆ 42   ┆ Tree  │
│ 0.614815  ┆ 0.514243 ┆ 0.6      ┆ 0.50463  ┆ … ┆ 0.1  ┆ 0            ┆ 42   ┆ Tree  │
│ 0.622222  ┆ 0.51405  ┆ 0.6      ┆ 0.50463  ┆ … ┆ 0.1  ┆ 0            ┆ 42   ┆ Tree  │
│ 0.622222  ┆ 0.515619 ┆ 0.6      ┆ 0.493506 ┆ … ┆ 0.1  ┆ 0            ┆ 42   ┆ Tree  │
│ …         ┆ …        ┆ …        ┆ …        ┆ … ┆ …    ┆ …            ┆ …    ┆ …     │
│ 1.0       ┆ 1.0      ┆ 0.933333 ┆ 0.93266  ┆ … ┆ 0.9  ┆ 2            ┆ 179  ┆ Tree  │
│ 1.0       ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 0.9  ┆ 2            ┆ 179  ┆ Tree  │
│ 1.0       ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 0.9  ┆ 2            ┆ 179  ┆ Tree  │
│ 1.0       ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 0.9  ┆ 2            ┆ 179  ┆ Tree  │
│ 1.0       ┆ 1.0      ┆ 0.933333 ┆ 0.93266  ┆ … ┆ 0.9  ┆ 2            ┆ 179  ┆ Tree  │
└───────────┴──────────┴──────────┴──────────┴───┴──────┴──────────────┴──────┴───────┘

In [12]:
cols = ["train acc", "train f1", "test acc", "test f1", 
               "adv acc", "adv f1", "adv distance", "clusters"]

def agg_metrics(cols):
    res = []
    for col in cols:
        res.extend([
            pl.col(col).mean().alias(f"{col}_mean"),
            pl.col(col).std().alias(f"{col}_std"),
            pl.col(col).map_batches(ci_lower, return_dtype=pl.Float32, returns_scalar=True).alias(f"{col}_ci_lb"),
            pl.col(col).map_batches(ci_upper, return_dtype=pl.Float32, returns_scalar=True).alias(f"{col}_ci_ub"),
        ])
    return res

In [13]:
df_stats = df.select(pl.exclude("seed")).group_by(
    pl.col("distribution"),
    pl.col("model"),
    pl.col("depth"),
    pl.col("bias")
).agg(
    agg_metrics(cols)
).sort([
    pl.col("distribution"),
    # pl.col("seed"),
    pl.col("depth"),
    pl.col("bias")
])

# df.with_columns(pl.col("train acc").gr)

In [14]:
df_stats.collect()

shape: (418, 36)
┌──────────────┬───────┬───────┬──────┬───┬──────────────┬─────────────┬─────────────┬─────────────┐
│ distribution ┆ model ┆ depth ┆ bias ┆ … ┆ clusters_mea ┆ clusters_st ┆ clusters_ci ┆ clusters_ci │
│ ---          ┆ ---   ┆ ---   ┆ ---  ┆   ┆ n            ┆ d           ┆ _lb         ┆ _ub         │
│ str          ┆ str   ┆ i32   ┆ f64  ┆   ┆ ---          ┆ ---         ┆ ---         ┆ ---         │
│              ┆       ┆       ┆      ┆   ┆ f64          ┆ f64         ┆ f32         ┆ f32         │
╞══════════════╪═══════╪═══════╪══════╪═══╪══════════════╪═════════════╪═════════════╪═════════════╡
│ circles      ┆ Tree  ┆ 1     ┆ 0.25 ┆ … ┆ 1.258065     ┆ 0.50869     ┆ 1.245053    ┆ 1.271076    │
│ circles      ┆ Tree  ┆ 1     ┆ 0.5  ┆ … ┆ 1.26         ┆ 0.504925    ┆ 1.24754     ┆ 1.27246     │
│ circles      ┆ Tree  ┆ 1     ┆ 0.75 ┆ … ┆ 1.26         ┆ 0.504925    ┆ 1.24754     ┆ 1.27246     │
│ circles      ┆ Tree  ┆ 1     ┆ 1.0  ┆ … ┆ 1.26         ┆ 0.504925    ┆ 1.24754     ┆ 1.27246     │
│ circles      ┆ Tree  ┆ 1     ┆ 1.25 ┆ … ┆ 1.26         ┆ 0.504925    ┆ 1.24754     ┆ 1.27246     │
│ …            ┆ …     ┆ …     ┆ …    ┆ … ┆ …            ┆ …           ┆ …           ┆ …           │
│ moons        ┆ Tree  ┆ 12    ┆ 2.0  ┆ … ┆ 9.966667     ┆ 1.956128    ┆ 9.879593    ┆ 10.05374    │
│ moons        ┆ Tree  ┆ 12    ┆ 2.25 ┆ … ┆ 9.8          ┆ 1.196486    ┆ 9.735351    ┆ 9.864649    │
│ moons        ┆ Tree  ┆ 12    ┆ 2.5  ┆ … ┆ 9.966667     ┆ 1.473521    ┆ 9.901075    ┆ 10.032258   │
│ moons        ┆ Tree  ┆ 12    ┆ 3.0  ┆ … ┆ 9.966667     ┆ 1.473521    ┆ 9.901075    ┆ 10.032258   │
│ moons        ┆ Tree  ┆ 13    ┆ 1.5  ┆ … ┆ 6.84         ┆ 1.556553    ┆ 6.785955    ┆ 6.894044    │
└──────────────┴───────┴───────┴──────┴───┴──────────────┴─────────────┴─────────────┴─────────────┘

In [ ]:
base = alt.Chart(
    df_stats.collect()
)

scale = alt.Scale(
    domain=["train acc_mean", "test acc_mean", "adv distance_mean"], 
    range=["blue", "red", "purple"]
)


dash_scale = alt.Scale(
    domain=["train acc_mean", "test acc_mean", "adv distance_mean"],
    range=[[2, 4], [1, 0], [8, 4]]  # [dash_length, gap_length]
)

# Chart for accuracy metrics (left y-axis)
acc_chart = base.mark_line(strokeWidth=2).transform_fold(
    fold=["train acc_mean", "test acc_mean"],
    as_=["variable", "value"]
).encode(
    x=alt.X("depth:Q").title("Depth"),
    y=alt.Y('value:Q').title("Accuracy").scale(zero=False),
    color=alt.Color('variable:N', scale=scale, title="Metric"),
    strokeDash=alt.StrokeDash('variable:N', scale=dash_scale)
)


# Chart for adversarial distance (right y-axis)
adv_chart = base.mark_line(strokeWidth=2).transform_fold(
    fold=["adv distance_mean"],
    as_=["variable", "value"]
).encode(
    x=alt.X("depth:Q").title("Depth"),
    y=alt.Y('value:Q').title("Adversarial Distance").axis(orient='right').scale(zero=False),
    color=alt.Color('variable:N', scale=scale, title="Metric"),
    strokeDash=alt.StrokeDash('variable:N', scale=dash_scale)

)

ci_band0 = base.mark_area(
    opacity=0.3,
    interpolate="basis",
).encode(
    x="depth:Q",
    y=alt.Y("train acc_ci_lb:Q").axis(title="Accuracy", orient="left"),
    y2=alt.Y2("train acc_ci_ub:Q"),
    color = alt.value("blue"),
)

ci_band1 = base.mark_area(
    opacity=0.3,
    interpolate="basis",
).encode(
    x="depth:Q",
    y=alt.Y("test acc_ci_lb:Q").axis(title="Accuracy", orient="left"),
    y2=alt.Y2("test acc_ci_ub:Q"),
    color = alt.value("red")
)

ci_band2 = base.mark_area(
    opacity=0.3,
    interpolate="basis",
).encode(
    x="depth:Q",
    y=alt.Y("adv distance_ci_lb:Q").axis(orient="right"),
    y2=alt.Y2("adv distance_ci_ub:Q"),
    color = alt.value("purple")
)

alt.layer(acc_chart + ci_band0 + ci_band1, adv_chart + ci_band2).resolve_scale(
    y='independent'
).facet(
    row="distribution",
    column="bias"
).resolve_scale(
    x="independent",
    y="independent"
)

alt.FacetChart(...)

: