In [12]:
import polars as pl
import numpy as np
from scipy import stats
import altair as alt

In [30]:
df = pl.scan_parquet("data/data_bias.parquet")

In [31]:
def ci_lower(x, confidence = .95):
    x = x.to_numpy()
    n = len(x)

    mean = np.mean(x)
    se = stats.sem(x)
    ci = se * stats.t.pdf((1 + confidence) / 2, n-1)

    return mean - ci

def ci_upper(x, confidence = .95):
    x = x.to_numpy()
    n = len(x)

    mean = np.mean(x)
    se = stats.sem(x)
    ci = se * stats.t.pdf((1 + confidence) / 2, n-1)

    return mean + ci

In [32]:
df.collect()

shape: (2_700, 12)
┌───────────┬──────────┬──────────┬──────────┬───┬──────┬──────────────┬──────┬───────┐
│ train acc ┆ train f1 ┆ test acc ┆ test f1  ┆ … ┆ bias ┆ distribution ┆ seed ┆ model │
│ ---       ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---  ┆ ---          ┆ ---  ┆ ---   │
│ f64       ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64  ┆ i64          ┆ i32  ┆ str   │
╞═══════════╪══════════╪══════════╪══════════╪═══╪══════╪══════════════╪══════╪═══════╡
│ 1.0       ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 0.1  ┆ 0            ┆ 42   ┆ Tree  │
│ 1.0       ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 0.1  ┆ 0            ┆ 42   ┆ Tree  │
│ 1.0       ┆ 1.0      ┆ 1.0      ┆ 1.0      ┆ … ┆ 0.1  ┆ 0            ┆ 42   ┆ Tree  │
│ 1.0       ┆ 1.0      ┆ 0.933333 ┆ 0.93266  ┆ … ┆ 0.1  ┆ 0            ┆ 42   ┆ Tree  │
│ 1.0       ┆ 1.0      ┆ 0.866667 ┆ 0.866667 ┆ … ┆ 0.1  ┆ 0            ┆ 42   ┆ Tree  │
│ …         ┆ …        ┆ …        ┆ …        ┆ … ┆ …    ┆ …            ┆ …    ┆ …     │
│ 0.888889  ┆ 0.885714 ┆ 0.933333 ┆ 0.93266  ┆ … ┆ 0.9  ┆ 2            ┆ 179  ┆ Tree  │
│ 0.844444  ┆ 0.835488 ┆ 1.0      ┆ 1.0      ┆ … ┆ 0.9  ┆ 2            ┆ 179  ┆ Tree  │
│ 0.859259  ┆ 0.852694 ┆ 0.866667 ┆ 0.861111 ┆ … ┆ 0.9  ┆ 2            ┆ 179  ┆ Tree  │
│ 0.859259  ┆ 0.852694 ┆ 0.866667 ┆ 0.861111 ┆ … ┆ 0.9  ┆ 2            ┆ 179  ┆ Tree  │
│ 0.859259  ┆ 0.852694 ┆ 0.866667 ┆ 0.861111 ┆ … ┆ 0.9  ┆ 2            ┆ 179  ┆ Tree  │
└───────────┴──────────┴──────────┴──────────┴───┴──────┴──────────────┴──────┴───────┘

In [33]:
cols = ["train acc", "train f1", "test acc", "test f1", 
               "adv acc", "adv f1", "adv distance", "clusters"]

def agg_metrics(cols):
    res = []
    for col in cols:
        res.extend([
            pl.col(col).mean().alias(f"{col}_mean"),
            pl.col(col).std().alias(f"{col}_std"),
            pl.col(col).map_batches(ci_lower, return_dtype=pl.Float32, returns_scalar=True).alias(f"{col}_ci_lb"),
            pl.col(col).map_batches(ci_upper, return_dtype=pl.Float32, returns_scalar=True).alias(f"{col}_ci_ub"),
        ])
    return res

In [34]:
df_stats = df.select(pl.exclude("seed")).group_by(
    pl.col("distribution"),
    pl.col("model"),
    # pl.col("seed"),
    pl.col("bias")
).agg(
    agg_metrics(cols)
).sort([
    pl.col("distribution"),
    # pl.col("seed"),
    # pl.col("depth"),
    pl.col("bias")
])

# df.with_columns(pl.col("train acc").gr)

In [35]:
df_stats.collect()

shape: (27, 35)
┌─────────────┬───────┬──────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ distributio ┆ model ┆ bias ┆ train       ┆ … ┆ clusters_m ┆ clusters_s ┆ clusters_c ┆ clusters_c │
│ n           ┆ ---   ┆ ---  ┆ acc_mean    ┆   ┆ ean        ┆ td         ┆ i_lb       ┆ i_ub       │
│ ---         ┆ str   ┆ f64  ┆ ---         ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ i64         ┆       ┆      ┆ f64         ┆   ┆ f64        ┆ f64        ┆ f32        ┆ f32        │
╞═════════════╪═══════╪══════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 0           ┆ Tree  ┆ 0.1  ┆ 1.0         ┆ … ┆ 1.92       ┆ 0.393893   ┆ 1.91028    ┆ 1.92972    │
│ 0           ┆ Tree  ┆ 0.2  ┆ 1.0         ┆ … ┆ 1.91       ┆ 0.378594   ┆ 1.900657   ┆ 1.919343   │
│ 0           ┆ Tree  ┆ 0.3  ┆ 1.0         ┆ … ┆ 1.91       ┆ 0.378594   ┆ 1.900657   ┆ 1.919343   │
│ 0           ┆ Tree  ┆ 0.4  ┆ 0.998593    ┆ … ┆ 1.91       ┆ 0.378594   ┆ 1.900657   ┆ 1.919343   │
│ 0           ┆ Tree  ┆ 0.5  ┆ 0.997185    ┆ … ┆ 1.91       ┆ 0.378594   ┆ 1.900657   ┆ 1.919343   │
│ …           ┆ …     ┆ …    ┆ …           ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 2           ┆ Tree  ┆ 0.5  ┆ 0.922889    ┆ … ┆ 1.97       ┆ 0.3        ┆ 1.962597   ┆ 1.977403   │
│ 2           ┆ Tree  ┆ 0.6  ┆ 0.910519    ┆ … ┆ 1.97       ┆ 0.3        ┆ 1.962597   ┆ 1.977403   │
│ 2           ┆ Tree  ┆ 0.7  ┆ 0.86437     ┆ … ┆ 1.97       ┆ 0.264193   ┆ 1.96348    ┆ 1.97652    │
│ 2           ┆ Tree  ┆ 0.8  ┆ 0.804741    ┆ … ┆ 1.97       ┆ 0.3        ┆ 1.962597   ┆ 1.977403   │
│ 2           ┆ Tree  ┆ 0.9  ┆ 0.787407    ┆ … ┆ 1.89       ┆ 0.314466   ┆ 1.88224    ┆ 1.89776    │
└─────────────┴───────┴──────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [36]:
base = alt.Chart(
    df_stats.collect()
)

scale = alt.Scale(
    domain=["train acc_mean", "test acc_mean", "adv distance_mean"], 
    range=["blue", "red", "purple"]
)


dash_scale = alt.Scale(
    domain=["train acc_mean", "test acc_mean", "adv distance_mean"],
    range=[[2, 4], [1, 0], [8, 4]]  # [dash_length, gap_length]
)

# Chart for accuracy metrics (left y-axis)
acc_chart = base.mark_line(strokeWidth=2).transform_fold(
    fold=["train acc_mean", "test acc_mean"],
    as_=["variable", "value"]
).encode(
    x=alt.X("bias:Q").title("Bias"),
    y=alt.Y('value:Q').title("Accuracy").scale(zero=False),
    color=alt.Color('variable:N', scale=scale, title="Metric"),
    strokeDash=alt.StrokeDash('variable:N', scale=dash_scale)
)


# Chart for adversarial distance (right y-axis)
adv_chart = base.mark_line(strokeWidth=2).transform_fold(
    fold=["adv distance_mean"],
    as_=["variable", "value"]
).encode(
    x=alt.X("bias:Q").title("Bias"),
    y=alt.Y('value:Q').title("Adversarial Distance").axis(orient='right').scale(zero=False),
    color=alt.Color('variable:N', scale=scale, title="Metric"),
    strokeDash=alt.StrokeDash('variable:N', scale=dash_scale)

)

ci_band0 = base.mark_area(
    opacity=0.3,
    interpolate="basis",
).encode(
    x="bias:Q",
    y=alt.Y("train acc_ci_lb:Q").axis(title="Accuracy", orient="left"),
    y2=alt.Y2("train acc_ci_ub:Q"),
    color = alt.value("blue"),
)

ci_band1 = base.mark_area(
    opacity=0.3,
    interpolate="basis",
).encode(
    x="bias:Q",
    y=alt.Y("test acc_ci_lb:Q").axis(title="Accuracy", orient="left"),
    y2=alt.Y2("test acc_ci_ub:Q"),
    color = alt.value("red")
)

ci_band2 = base.mark_area(
    opacity=0.3,
    interpolate="basis",
).encode(
    x="bias:Q",
    y=alt.Y("adv distance_ci_lb:Q").axis(orient="right"),
    y2=alt.Y2("adv distance_ci_ub:Q"),
    color = alt.value("purple")
)

alt.layer(acc_chart + ci_band0 + ci_band1, adv_chart + ci_band2).resolve_scale(
    y='independent'
).facet(
    row="distribution",
    column="seed"
).resolve_scale(
    x="independent",
    y="independent"
)

alt.FacetChart(...)